# Generated by Django 5.2.10 on 2026-01-15 04:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='primarySubject',
            new_name='primary_subject',
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.subject')),
            ],
            options={
                'db_table': 'certificates',
                'indexes': [models.Index(fields=['student'], name='certificate_student_e19697_idx'), models.Index(fields=['subject'], name='certificate_subject_1d9201_idx')],
            },
        ),
    ]
