# Generated by Django 5.2.10 on 2026-01-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_primarysubject_student_primary_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='archived',
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
