# Generated by Django 5.2.10 on 2026-01-15 05:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_student_archived_student_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='active',
            new_name='is_active',
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=13)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.student')),
            ],
            options={
                'db_table': 'contacts',
                'indexes': [models.Index(fields=['student'], name='contacts_student_d69a7e_idx')],
            },
        ),
    ]
