# Generated by Django 5.2.10 on 2026-01-16 04:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_group_groupmembership_group_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='joined_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
