# Generated by Django 5.2.10 on 2026-01-16 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_groupmembership_joined_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='primary_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
    ]
