# Generated by Django 5.2.10 on 2026-01-16 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_student_primary_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='primary_subject',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
    ]
