# Generated by Django 5.2.10 on 2026-01-16 06:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_student_primary_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_at', models.DateField()),
                ('end_at', models.DateField()),
                ('amount', models.IntegerField()),
                ('is_debtor', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.student')),
            ],
            options={
                'db_table': 'payments',
                'indexes': [models.Index(fields=['group'], name='payments_group_i_d67c2c_idx'), models.Index(fields=['student'], name='payments_student_5b85b3_idx')],
                'constraints': [models.UniqueConstraint(fields=('group', 'student'), name='uniq_payment')],
            },
        ),
    ]
